title: NHS Wales Open Architecture Docs

company_name: NHS Wales

baseurl: /open-architecture

plugins:
  - jekyll-redirect-from

github_editme_path: /nwisbeta/open-architecture/edit/master/

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
